language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t paolo1010/docker-react -f Dockerfile.dev .

script:
  - docker -e CI=true run paolo1010/docker-react npm run test